branches:
  only:
    - master
    - develop
language: node_js
node_js:
  - 6
  - 7
  - 8
env:
  global:
    - NODE_ENV=development
before_install:
  - npm install react@16.2.0
  - npm install react-dom@16.2.0
install:
  - npm install
script:
  - npm test
  - npm run lint
